In [2]:
import numpy as np

In [3]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [7]:
len(a [a < 0])

4

In [8]:
len(a [a > 0])

5

In [12]:
positive_a = (a [a > 0])

In [15]:
len(positive_a [positive_a % 2 == 0])

3

In [17]:
a_plus_three = a + 3

In [18]:
len(a_plus_three [a_plus_three > 0])

10

In [19]:
a_squared = a ** 2

In [20]:
a_squared.mean()

74.0

In [21]:
a_squared.std()

144.0243035046516

In [22]:
a_squared

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [23]:
mean_of_a = a.mean()

In [24]:
centering_a = a - mean_of_a

In [25]:
centering_a

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [26]:
centering_a.mean()

0.0

In [27]:
standard_dev_of_a = a.std()

In [29]:
z_score_a = centering_a/standard_dev_of_a

In [30]:
z_score_a

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [44]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [45]:
def sum_of_a(a):
    total = 0
    for num in a:
        total += num
    return total


In [46]:
sum_of_a = sum_of_a(a) 

In [47]:
sum_of_a

55

In [48]:
min(a)

1

In [49]:
max(a)

10

In [50]:
def mean(a):
    total = 0
    for num in a:
        total += num
    return total/ len(a)

In [51]:
mean_of_a = mean(a)

In [52]:
mean_of_a

5.5

In [58]:
def product(a):
    total = 1
    for num in a:
        total = total * num
    return total

In [59]:
product(a)

3628800

In [61]:
def square(a):
    squared_list = []
    for num in a:
        num = num ** 2
        squared_list.append(num)
    return squared_list
squares_of_a = square(a)
squares_of_a 

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [62]:
def odds(a):
    odd_list = []
    for num in a:
        if num % 2 != 0:
            odd_list.append(num)
    return odd_list
odds_in_a = odds(a)
odds_in_a

[1, 3, 5, 7, 9]

In [64]:
def evens(a):
    even_list = []
    for num in a:
        if num % 2 != 1:
            even_list.append(num)
    return even_list
evens_in_a = evens(a)
evens_in_a

[2, 4, 6, 8, 10]

In [65]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [66]:
np.max(b)

8

In [67]:
np.square(b)

array([[ 9, 16, 25],
       [36, 49, 64]])

In [68]:
np.shape(b)

(2, 3)

In [69]:
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [127]:
np.refactor(b)

AttributeError: module 'numpy' has no attribute 'refactor'

In [75]:
np.reshape(b,(1,6))

array([[3, 4, 5, 6, 7, 8]])

In [76]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [77]:
c = np.array(c)

In [78]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
np.max(c)

9

In [80]:
np.min(c)

1

In [82]:
np.sum(c)

45

In [83]:
np.product(c)

362880

In [86]:
np.var(c)

6.666666666666667

In [88]:
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [89]:
np.transpose(c)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [90]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
np.sum((c * c_transposed))

261

In [93]:
c_transposed = np.transpose(c)

In [95]:
np.product((c * c_transposed))

131681894400

In [102]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [107]:
d = np.array(d)

In [108]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [109]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [110]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [122]:
positive_d = (d[d > 0])

In [130]:
np.even(d)

AttributeError: module 'numpy' has no attribute 'even'

In [123]:
positive_d

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [124]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [125]:
len(np.unique(d))

11

In [126]:
np.shape(d)

(3, 6)

In [129]:
transposed_d = np.transpose(d)
np.shape(transposed_d)

(6, 3)

In [131]:
odd_only = (d[d % 2 != 0])
odd_only

array([ 45,  45,  45, -45, -45])

In [132]:
even_only = (d[d % 2 == 0])
even_only

array([ 90,  30,   0, 120, 180, -90, -30, 270,  90,   0,  60,  90, 180])

In [136]:
help(np.shape(d))

Help on tuple object:

class tuple(object)
 |  tuple(iterable=(), /)
 |  
 |  Built-in immutable sequence.
 |  
 |  If no argument is given, the constructor returns an empty tuple.
 |  If iterable is specified the tuple is initialized from iterable's items.
 |  
 |  If the argument is a tuple, the return value is the same object.
 |  
 |  Built-in subclasses:
 |      asyncgen_hooks
 |      UnraisableHookArgs
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __getnewargs__(self, /)
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __iter__(self, /)
 |

In [140]:
np.reshape(d,(9,2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])